title: "H.C. Ivan Shih"
author: "Ivan Shih"
description: "Welcome to Ivan Shih's website!"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: true        # show article excerpts on the home page
show_frame: false           # adds a gray frame to the site
show_sidebar: true        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {title: "About", file: "index.md"}
  - {title: "Publications", file: "publications.md"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:ivanshih@umich.edu"}
  - {title: Linkedin, icon: linkedin-in, url: "https://www.linkedin.com/in/hsin-cheng-shih/"}
  - {title: GoogleScholar, icon: user-graduate, url: "https://scholar.google.com.tw/citations?user=00cIJo8AAAAJ&hl=zh-TW"}
  - {title: Scoups, icon: , url: "https://www.scopus.com/authid/detail.uri?authorId=57613506000"}
  # - {title: Subscribe, icon: rss, url: "/feed.xml"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
 - jekyll-sitemap
